# Disabled Jekyll Pages workflow (project is not Jekyll). Using Vite build via deploy.yml instead.
name: DISABLED - Jekyll GitHub Pages

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Jekyll workflow disabled. Using Vite build in .github/workflows/deploy.yml"
